spring:
  boot:
    admin:
      client:
        enabled: ${BDP_SPRINGBOOT_ADMIN_ENABLED:false}
        url: ${BDP_SPRINGBOOT_ADMIN_URL:http://localhost:8080}
management:
  info:
    os:
      enabled: true
    process:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, flayway, scheduledtasks, loggers, caches, mappings
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState