spring:
  application:
    developed-by: Nemodev
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      read-unknown-enum-values-using-default-value: true
  docker:
    compose:
      enabled: false
  threads:
    virtual:
      enabled: true
